language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    - hhvm
    - hhvm-nightly
matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm-nightly
script:
    - composer install
    - phpunit
